global:
  evaluation_interval: 30s
  scrape_interval: 5s
scrape_configs:
  - job_name: otel-collector
#  - job_name: orders-api
    static_configs:
      - targets:
          - 'otel-collector:8889'
#          - 'orders.api:8080' # for manual scrapping from the service itself